name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
#  bundled-test:
#    strategy:
#      matrix:
#        os: [
#          ubuntu-latest,
#          macos-latest,
#          macos-14, # macOS arm runner
#          windows-latest,
#        ]
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/checkout@v3
#      - name: Test bundled
#        run: |
#          cargo b --features bundled -vv
#          cargo t --features bundled create
#          cargo t --features bundled --examples
#      - name: Test from-source
#        run: |
#          cargo b --features from-source -vv
#          cargo t --features from-source create
#          cargo t --features from-source --examples


#  macos-from-source:
#    strategy:
#      matrix:
#        os: [
#          macos-latest,
#          macos-14,
#        ]
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/checkout@v3
#      - name: Test from-source
#        run: |
#          brew install bison
#          cargo b --features from-source -vv
#          cargo t --features from-source create
#          cargo t --features from-source --examples

#  ubuntu-from-source:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Test from-source
#        run: |
#          cargo b --features from-source -vv
#          cargo t --features from-source create
#          cargo t --features from-source --examples


  windows-from-source:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test from-source
        run: |
          cargo b --features from-source -vv
          cargo t --features from-source create
          cargo t --features from-source --examples