name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
#  bundled-test:
#    strategy:
#      matrix:
#        os: [
#          ubuntu-latest,
#          macos-latest,
#          macos-14, # macOS arm runner
#          windows-latest,
#        ]
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/checkout@v3
#      - name: Test bundled
#        run: |
#          cargo b --features bundled -vv
#          cargo t --features bundled create
#          cargo t --features bundled --examples
#      - name: Test from-source
#        run: |
#          cargo b --features from-source -vv
#          cargo t --features from-source create
#          cargo t --features from-source --examples


#  macos-from-source:
#    strategy:
#      matrix:
#        os: [
#          macos-latest,
#          macos-14,
#        ]
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/checkout@v3
#      - name: Test from-source
#        run: |
#          brew install bison
#          cargo b --features from-source -vv
#          cargo t --features from-source create
#          cargo t --features from-source --examples

#  ubuntu-from-source:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Test from-source
#        run: |
#          cargo b --features from-source -vv
#          cargo t --features from-source create
#          cargo t --features from-source --examples


  windows-from-source:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgArguments: 'tbb'
          vcpkgDirectory: '${{ runner.workspace }}/vcpkg/'
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
          vcpkgGitURL: 'https://github.com/microsoft/vcpkg.git'
          setupOnly: true

      - name: Cache vcpkg artifacts
        uses: actions/cache@v4
        with:
          path: |
            ${{ runner.workspace }}/vcpkg/installed
            !**/packages
          key: ${{ runner.os }}-tbb-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-tbb-

      - name: Test from-source
        run: |
          echo "${{ runner.workspace }}/vcpkg" >> $GITHUB_PATH
          cargo b --features from-source -vv
          cargo t --features from-source create
          cargo t --features from-source --examples