name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  from-source-test:
    strategy:
      matrix:
        os: [
          ubuntu-24.04-arm
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install bison
        if: ${{ matrix.os == 'macos-13' || matrix.os == 'macos-14' }}
        run: |
          brew install bison gcc
      - name: Test from-source
        run: |
          cargo b --features from-source -vv
          cargo t --features from-source create
          cargo t --features from-source --examples
