name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bundled-test:
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          macos-13,
          macos-14, # macOS arm runner
          windows-latest,
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Test bundled
        run: |
          cargo b --features bundled --release
          cargo t --features bundled --release create
          cargo t --features bundled --release --examples     

  bundled-debug-test:
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          macos-13,
          macos-14, # macOS arm runner
          windows-latest,
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Test bundled
        run: |
          cargo b --features bundled
          cargo t --features bundled create
          cargo t --features bundled --examples   

  from-source-test:
    strategy:
      matrix:
        os: [
          macos-13,
          macos-14,
          ubuntu-latest,
          windows-latest,
          ubuntu-24.04-arm
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install bison
        if: ${{ matrix.os == 'macos-13' || matrix.os == 'macos-14' }}
        run: |
          brew install bison gcc
      - name: Test from-source
        run: |
          cargo b --features from-source -vv
          cargo t --features from-source create
          cargo t --features from-source --examples

  linux-conda-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          allow-softlinks: true

      - name: Install dependencies (SCIPOptSuite)
        run: |
          conda install -y --prefix $CONDA/envs/test --channel conda-forge scip
          echo "LD_LIBRARY_PATH=$CONDA/envs/test/lib" >> "${GITHUB_ENV}"
          echo "CONDA_PREFIX=$CONDA/envs/test" >> "${GITHUB_ENV}"

      - name: Test
        run: |
          cargo b -vv
          cargo t create
          cargo t --examples